/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInterventionsIndexRouteImport } from './routes/_app.interventions.index'
import { Route as AppEquipmentIndexRouteImport } from './routes/_app.equipment.index'
import { Route as AppInterventionsIdRouteImport } from './routes/_app.interventions.$id'
import { Route as AppEquipmentIdRouteImport } from './routes/_app.equipment.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsIndexRoute = AppInterventionsIndexRouteImport.update({
  id: '/interventions/',
  path: '/interventions/',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentIndexRoute = AppEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsIdRoute = AppInterventionsIdRouteImport.update({
  id: '/interventions/$id',
  path: '/interventions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentIdRoute = AppEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/notifications': typeof AppNotificationsRoute
  '/team': typeof AppTeamRoute
  '/equipment/$id': typeof AppEquipmentIdRoute
  '/interventions/$id': typeof AppInterventionsIdRoute
  '/equipment/': typeof AppEquipmentIndexRoute
  '/interventions/': typeof AppInterventionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/notifications': typeof AppNotificationsRoute
  '/team': typeof AppTeamRoute
  '/equipment/$id': typeof AppEquipmentIdRoute
  '/interventions/$id': typeof AppInterventionsIdRoute
  '/equipment': typeof AppEquipmentIndexRoute
  '/interventions': typeof AppInterventionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/equipment/$id': typeof AppEquipmentIdRoute
  '/_app/interventions/$id': typeof AppInterventionsIdRoute
  '/_app/equipment/': typeof AppEquipmentIndexRoute
  '/_app/interventions/': typeof AppInterventionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/team'
    | '/equipment/$id'
    | '/interventions/$id'
    | '/equipment/'
    | '/interventions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/team'
    | '/equipment/$id'
    | '/interventions/$id'
    | '/equipment'
    | '/interventions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/notifications'
    | '/_app/team'
    | '/_app/equipment/$id'
    | '/_app/interventions/$id'
    | '/_app/equipment/'
    | '/_app/interventions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interventions/': {
      id: '/_app/interventions/'
      path: '/interventions'
      fullPath: '/interventions/'
      preLoaderRoute: typeof AppInterventionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment/': {
      id: '/_app/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AppEquipmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interventions/$id': {
      id: '/_app/interventions/$id'
      path: '/interventions/$id'
      fullPath: '/interventions/$id'
      preLoaderRoute: typeof AppInterventionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment/$id': {
      id: '/_app/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof AppEquipmentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppEquipmentIdRoute: typeof AppEquipmentIdRoute
  AppInterventionsIdRoute: typeof AppInterventionsIdRoute
  AppEquipmentIndexRoute: typeof AppEquipmentIndexRoute
  AppInterventionsIndexRoute: typeof AppInterventionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppTeamRoute: AppTeamRoute,
  AppEquipmentIdRoute: AppEquipmentIdRoute,
  AppInterventionsIdRoute: AppInterventionsIdRoute,
  AppEquipmentIndexRoute: AppEquipmentIndexRoute,
  AppInterventionsIndexRoute: AppInterventionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
